echo "🚀 Running Comprehensive AI Feature Tests..."
echo "====================================="
echo ""
echo "1. AI Forecasting Tests..."
npx playwright test ai-forecasting.spec.ts --reporter=line --timeout=120000 --project="Desktop Chrome" || echo "❌ AI Forecasting tests failed"
echo ""
echo "2. Skill Matching Tests..."  
npx playwright test skill-matching.spec.ts --reporter=line --timeout=120000 --project="Desktop Chrome" || echo "❌ Skill Matching tests failed"
echo ""
echo "3. Optimization Tests..."
npx playwright test optimization.spec.ts --reporter=line --timeout=120000 --project="Desktop Chrome" || echo "❌ Optimization tests failed"
echo ""
echo "✅ All AI feature tests completed!"
