# Prometheus Configuration for Production Monitoring
# ==================================================
# Comprehensive monitoring stack for empirical evidence generation

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Application metrics
  - job_name: 'resource-planning-api'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:3001']
    metrics_path: '/api/metrics'
    scrape_timeout: 10s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']

  # Container metrics
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']

  # PostgreSQL metrics
  - job_name: 'postgres-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis metrics
  - job_name: 'redis-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx metrics
  - job_name: 'nginx-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Custom business metrics
  - job_name: 'business-metrics'
    scrape_interval: 30s
    static_configs:
      - targets: ['app:3001']
    metrics_path: '/api/business-metrics'
    
  # Performance benchmarks
  - job_name: 'performance-benchmarks'
    scrape_interval: 60s
    static_configs:
      - targets: ['app:3001']
    metrics_path: '/api/performance-metrics'

  # Load test results (for continuous monitoring)
  - job_name: 'load-test-results'
    scrape_interval: 300s # Every 5 minutes
    static_configs:
      - targets: ['load-tester:3002']