export const __esModule: boolean;
export const DepartmentModel: typeof Department_1.DepartmentModel;
export const SkillModel: typeof Skill_1.SkillModel;
export const EmployeeModel: typeof Employee_1.EmployeeModel;
export const EmployeeSkillModel: typeof EmployeeSkill_1.EmployeeSkillModel;
export const CapacityHistoryModel: typeof CapacityHistory_1.CapacityHistoryModel;
export const ProjectModel: typeof project_model_1.ProjectModel;
export const ResourceAllocationModel: typeof ResourceAllocation_1.ResourceAllocationModel;
export const WorkingAllocationModel: typeof working_allocation_model_1.WorkingAllocationModel;
export const SkillRequirementModel: typeof SkillRequirement_1.SkillRequirementModel;
export const ProjectTask: typeof ProjectTask_1.ProjectTask;
export const TaskDependency: typeof TaskDependency_1.TaskDependency;
export const BudgetModel: typeof Budget_1.BudgetModel;
export const ResourceCostModel: typeof ResourceCost_1.ResourceCostModel;
export function initializeModels(pool: any): void;
import Department_1 = require("./Department");
import Skill_1 = require("./Skill");
import Employee_1 = require("./Employee");
import EmployeeSkill_1 = require("./EmployeeSkill");
import CapacityHistory_1 = require("./CapacityHistory");
import project_model_1 = require("./project.model");
import ResourceAllocation_1 = require("./ResourceAllocation");
import working_allocation_model_1 = require("./working-allocation.model");
import SkillRequirement_1 = require("./SkillRequirement");
import ProjectTask_1 = require("./ProjectTask");
import TaskDependency_1 = require("./TaskDependency");
import Budget_1 = require("./Budget");
import ResourceCost_1 = require("./ResourceCost");
//# sourceMappingURL=index.d.ts.map